<?php
/**
 * The cast, and what each of them is like — server side.
 * ------------------------------------------------------------------
 * GENERATED by tools/sync-candidates.mjs from js/data/candidates.js.
 * Do not edit by hand: edit the JavaScript and run the tool.
 *
 * A solo game rolls in the browser and a multiplayer game rolls here. Both
 * multiply a campaign by the candidate's support in that region, so these
 * numbers and the ones in the JavaScript have to be the same numbers. The
 * campaign suite fails if this file is out of date.
 */

class Candidates
{
    /** Neutral, in the units regionalSupport is written in. */
    public const REGION_NEUTRAL = 50;

    /** What a 100 or a 0 is worth, either side of neutral. */
    public const REGION_SWING = 0.2;

    private const STATS = [
        'a1' => [
            'popularity' => 61,
            'corruption' => 14,
            'leadership' => 74,
            'campaignStrength' => 79,
            'regionalSupport' => [
                'majha' => 48,
                'doaba' => 55,
                'malwa' => 71,
            ],
        ],
        'a2' => [
            'popularity' => 68,
            'corruption' => 8,
            'leadership' => 66,
            'campaignStrength' => 58,
            'regionalSupport' => [
                'majha' => 72,
                'doaba' => 61,
                'malwa' => 44,
            ],
        ],
        'a3' => [
            'popularity' => 74,
            'corruption' => 38,
            'leadership' => 82,
            'campaignStrength' => 51,
            'regionalSupport' => [
                'majha' => 66,
                'doaba' => 47,
                'malwa' => 63,
            ],
        ],
        'a4' => [
            'popularity' => 71,
            'corruption' => 19,
            'leadership' => 58,
            'campaignStrength' => 73,
            'regionalSupport' => [
                'majha' => 43,
                'doaba' => 52,
                'malwa' => 84,
            ],
        ],
        'a5' => [
            'popularity' => 52,
            'corruption' => 11,
            'leadership' => 77,
            'campaignStrength' => 62,
            'regionalSupport' => [
                'majha' => 57,
                'doaba' => 76,
                'malwa' => 49,
            ],
        ],
        'a6' => [
            'popularity' => 83,
            'corruption' => 31,
            'leadership' => 54,
            'campaignStrength' => 86,
            'regionalSupport' => [
                'majha' => 61,
                'doaba' => 58,
                'malwa' => 60,
            ],
        ],
        'a7' => [
            'popularity' => 69,
            'corruption' => 9,
            'leadership' => 88,
            'campaignStrength' => 44,
            'regionalSupport' => [
                'majha' => 78,
                'doaba' => 54,
                'malwa' => 51,
            ],
        ],
        'a8' => [
            'popularity' => 64,
            'corruption' => 26,
            'leadership' => 63,
            'campaignStrength' => 76,
            'regionalSupport' => [
                'majha' => 55,
                'doaba' => 81,
                'malwa' => 46,
            ],
        ],
        'a9' => [
            'popularity' => 47,
            'corruption' => 6,
            'leadership' => 69,
            'campaignStrength' => 81,
            'regionalSupport' => [
                'majha' => 52,
                'doaba' => 63,
                'malwa' => 58,
            ],
        ],
        'a10' => [
            'popularity' => 58,
            'corruption' => 47,
            'leadership' => 71,
            'campaignStrength' => 88,
            'regionalSupport' => [
                'majha' => 64,
                'doaba' => 44,
                'malwa' => 69,
            ],
        ],
    ];

    /**
     * What a face is worth, with a safe answer for one nobody wrote down.
     *
     * An id from a future list, or a save older than this table, is neutral
     * everywhere rather than an error — the same fallback the JavaScript uses.
     */
    public static function statsFor(string $avatarId): array
    {
        if (isset(self::STATS[$avatarId])) {
            return self::STATS[$avatarId];
        }

        return [
            'popularity' => 50,
            'corruption' => 25,
            'leadership' => 50,
            'campaignStrength' => 50,
            'regionalSupport' => ['majha' => 50, 'doaba' => 50, 'malwa' => 50],
        ];
    }

    /** Every id this table knows, for the tool that checks the two agree. */
    public static function ids(): array
    {
        return array_keys(self::STATS);
    }
}
