<?php
/**
 * Player profiles, achievements and the global counters.
 * ------------------------------------------------------------------
 * Everything on the home screen — players, elections, governments formed, the
 * leaderboard, party performance — is counted here from games that actually
 * finished. Nothing is seeded, nothing is estimated. A brand new installation
 * reports zero, and says zero, until somebody plays.
 *
 * One honesty problem is worth stating plainly, because it shaped the design.
 * A solo game runs entirely in the browser: the server never sees a roll and
 * cannot tell a real result from a crafted request. So a solo result is
 * recorded as *self-reported*. It counts on the player's own profile, where it
 * is their own business, and it is excluded from the global leaderboard, where
 * it would be an invitation. Games the server ran itself are verified, and
 * those are what rank.
 *
 * Profiles are keyed by an id the browser generates and keeps. That is a
 * deliberately low bar — it is a game, not a bank — but it means a profile
 * carries no email, no phone number and nothing else a player did not choose
 * to type. The only personal thing stored is the display name they picked.
 */
declare(strict_types=1);

final class Profiles
{
    private string $dir;
    private array $config;

    public function __construct(string $dataDir, array $config)
    {
        $this->dir = rtrim($dataDir, '/\\') . '/profiles';
        $this->config = $config['profiles'];

        if (!is_dir($this->dir)) {
            @mkdir($this->dir, 0700, true);
        }
        // The same guards FileStore uses: this directory must never be
        // readable over the web.
        $guard = $this->dir . '/.htaccess';
        if (!file_exists($guard)) {
            @file_put_contents($guard, "Require all denied\nDeny from all\n");
        }
    }

    /* ---------------------------------------------------------- storage */

    private function pathFor(string $id): string
    {
        return $this->dir . '/' . $id . '.json';
    }

    /** Ids are generated by the client, so never trust one into a filename. */
    public static function cleanId(string $id): string
    {
        $id = preg_replace('/[^a-f0-9]/i', '', $id) ?? '';
        return strlen($id) >= 16 && strlen($id) <= 64 ? strtolower($id) : '';
    }

    public static function cleanName(string $name): string
    {
        $name = trim(strip_tags($name));
        $name = preg_replace('/\s+/u', ' ', $name) ?? '';
        return mb_substr($name, 0, 32);
    }

    public function load(string $id): ?array
    {
        $id = self::cleanId($id);
        if ($id === '') {
            return null;
        }
        $raw = @file_get_contents($this->pathFor($id));
        if ($raw === false) {
            return null;
        }
        $data = json_decode($raw, true);
        return is_array($data) ? $data : null;
    }

    private function save(array $profile): void
    {
        $path = $this->pathFor($profile['id']);
        $tmp = $path . '.' . getmypid() . '.tmp';
        if (@file_put_contents($tmp, json_encode($profile, JSON_UNESCAPED_UNICODE), LOCK_EX) !== false) {
            @rename($tmp, $path);
        }
    }

    /** A blank profile. Every counter starts where it should: at nothing. */
    public static function blank(string $id, string $name, string $portraitSeed): array
    {
        $now = time();
        return [
            'id' => $id,
            'name' => $name,
            'portraitSeed' => $portraitSeed,
            'createdAt' => $now,
            'lastSeen' => $now,

            'played' => 0,
            'won' => 0,
            'seatsTotal' => 0,
            'bestResult' => 0,
            'coalitionWins' => 0,
            'verifiedPlayed' => 0,
            'verifiedWon' => 0,
            'verifiedSeats' => 0,

            'byParty' => [],
            'achievements' => [],
            'history' => [],
        ];
    }

    /** Find a profile, or start one. */
    public function ensure(string $id, string $name, string $portraitSeed): array
    {
        $id = self::cleanId($id);
        if ($id === '') {
            return [];
        }
        $profile = $this->load($id);
        if ($profile === null) {
            $profile = self::blank($id, self::cleanName($name) ?: 'Player', $portraitSeed);
            $this->save($profile);
            $this->bumpCounter('players');
            return $profile;
        }

        // A player may rename themselves; nothing else about them changes here.
        $clean = self::cleanName($name);
        if ($clean !== '' && $clean !== $profile['name']) {
            $profile['name'] = $clean;
        }
        if ($portraitSeed !== '') {
            $profile['portraitSeed'] = $portraitSeed;
        }
        $profile['lastSeen'] = time();
        $this->save($profile);
        return $profile;
    }

    /* ------------------------------------------------------- recording */

    /**
     * Record one finished election against a profile.
     *
     * $result is what the game knows: the party played, seats won, whether
     * they took office, whether it was through a coalition, what they spent,
     * and whether they were behind at round ten. $verified says whether the
     * server ran the game itself.
     */
    public function record(string $id, array $result, bool $verified): ?array
    {
        $profile = $this->load(self::cleanId($id));
        if ($profile === null) {
            return null;
        }

        $party = (string) ($result['party'] ?? '');
        $seats = max(0, (int) ($result['seats'] ?? 0));
        $won = !empty($result['won']);
        $coalition = !empty($result['coalition']);

        $profile['played']++;
        $profile['seatsTotal'] += $seats;
        $profile['bestResult'] = max((int) $profile['bestResult'], $seats);
        if ($won) {
            $profile['won']++;
        }
        if ($won && $coalition) {
            $profile['coalitionWins']++;
        }

        if ($verified) {
            $profile['verifiedPlayed']++;
            $profile['verifiedSeats'] += $seats;
            if ($won) {
                $profile['verifiedWon']++;
            }
        }

        if ($party !== '') {
            $row = $profile['byParty'][$party] ?? ['played' => 0, 'won' => 0, 'seats' => 0];
            $row['played']++;
            $row['seats'] += $seats;
            if ($won) {
                $row['won']++;
            }
            $profile['byParty'][$party] = $row;
        }

        $profile['history'][] = [
            'at' => time(),
            'party' => $party,
            'seats' => $seats,
            'won' => $won,
            'coalition' => $coalition,
            'outcome' => (string) ($result['outcome'] ?? ''),
            'verified' => $verified,
        ];
        if (count($profile['history']) > 50) {
            $profile['history'] = array_slice($profile['history'], -50);
        }

        $profile = $this->awardAchievements($profile, $result, $won, $seats, $coalition);
        $this->save($profile);

        // Party performance is per player, because four people playing one
        // election is four party campaigns. The election itself is counted
        // once, by countElection(), and only for a game the server ran.
        if ($verified && $party !== '') {
            $this->bumpParty($party, $won);
        }

        return $profile;
    }

    /**
     * Count one finished election.
     *
     * Called once per game, not once per player: four people contesting one
     * election is still one election. Only ever called for a game the server
     * played itself — a result a browser reports about its own solo game
     * counts on that player's profile and nowhere else, because there is no
     * way to tell a real one from a crafted request.
     */
    public function countElection(bool $governmentFormed, bool $byCoalition): void
    {
        $c = $this->counters();
        $c['elections'] = (int) ($c['elections'] ?? 0) + 1;
        if ($governmentFormed) {
            $c['governments'] = (int) ($c['governments'] ?? 0) + 1;
            if ($byCoalition) {
                $c['coalitions'] = (int) ($c['coalitions'] ?? 0) + 1;
            }
        }
        $this->writeCounters($c);
    }

    /** Which of the configured achievements this result earns. */
    private function awardAchievements(
        array $profile,
        array $result,
        bool $won,
        int $seats,
        bool $coalition
    ): array {
        $have = array_column($profile['achievements'], 'id');
        $earn = [];

        if ($won && !in_array('firstwin', $have, true)) {
            $earn[] = 'firstwin';
        }
        if ($won && $seats >= 59) {
            $earn[] = 'majority';
        }
        if ($won && $seats >= 75) {
            $earn[] = 'landslide';
        }
        if ($won && $coalition) {
            $earn[] = 'kingmaker';
        }
        if ($won && !empty($result['behindAtTen'])) {
            $earn[] = 'comeback';
        }
        if ($won && isset($result['spent']) && (int) $result['spent'] < 30000000) {
            $earn[] = 'frugal';
        }
        if ($won && !empty($result['usedHighRisk'])) {
            $earn[] = 'risktaker';
        }

        foreach ($earn as $id) {
            if (in_array($id, $have, true)) {
                continue;
            }
            $profile['achievements'][] = ['id' => $id, 'at' => time()];
            $have[] = $id;
        }
        return $profile;
    }

    /* ---------------------------------------------------------- scoring */

    /**
     * A player's leaderboard score. Verified games only, and weighted towards
     * winning rather than turning up — grinding games should not climb it.
     */
    public function scoreOf(array $profile): int
    {
        $s = $this->config['score'];
        return (int) round(
            (int) $profile['verifiedWon'] * (int) $s['perWin']
            + (int) $profile['verifiedSeats'] * (int) $s['perSeat']
            + (int) $profile['coalitionWins'] * (int) $s['perCoalitionWin']
            + count($profile['achievements']) * (int) $s['perAchievement']
            + (int) $profile['verifiedPlayed'] * (int) $s['perGamePlayed']
        );
    }

    /** Level, on a widening curve so the early ones come quickly. */
    public function levelOf(array $profile): array
    {
        $cfg = $this->config['level'];
        $score = $this->scoreOf($profile);

        $level = 1;
        $need = (int) $cfg['base'];
        $spent = 0;
        while ($level < (int) $cfg['maxLevel'] && $score >= $spent + $need) {
            $spent += $need;
            $level++;
            $need = (int) round($need * (float) $cfg['growth']);
        }
        return [
            'level' => $level,
            'score' => $score,
            'into' => $score - $spent,
            'need' => $need,
        ];
    }

    /* -------------------------------------------------------- the view */

    /**
     * A profile as clients see it. Public game statistics and nothing else —
     * no ids beyond the one the player already has, and nothing they did not
     * choose to type.
     */
    public function publicView(array $profile, array $config): array
    {
        $level = $this->levelOf($profile);
        $earned = array_column($profile['achievements'], 'id');

        $favourite = null;
        $best = 0;
        foreach (($profile['byParty'] ?? []) as $party => $row) {
            if ($row['played'] > $best) {
                $best = $row['played'];
                $favourite = $party;
            }
        }

        return [
            'name' => $profile['name'],
            'portraitSeed' => $profile['portraitSeed'],
            'played' => (int) $profile['played'],
            'won' => (int) $profile['won'],
            'winRate' => $profile['played'] > 0
                ? (int) round(($profile['won'] / $profile['played']) * 100)
                : 0,
            'seatsTotal' => (int) $profile['seatsTotal'],
            'bestResult' => (int) $profile['bestResult'],
            'coalitionWins' => (int) $profile['coalitionWins'],
            'favouriteParty' => $favourite,
            'byParty' => $profile['byParty'] ?? (object) [],
            'level' => $level['level'],
            'score' => $level['score'],
            'levelInto' => $level['into'],
            'levelNeed' => $level['need'],
            'verifiedPlayed' => (int) $profile['verifiedPlayed'],
            'achievements' => array_map(static function ($a) use ($config, $earned) {
                return $a;
            }, array_values(array_map(static function ($a) {
                return ['id' => $a['id'], 'at' => $a['at']];
            }, $profile['achievements']))),
            'history' => array_slice(array_reverse($profile['history'] ?? []), 0, 20),
        ];
    }

    /* ------------------------------------------------- global counters */

    private function countersPath(): string
    {
        return $this->dir . '/../counters.json';
    }

    public function counters(): array
    {
        $raw = @file_get_contents($this->countersPath());
        $data = $raw === false ? null : json_decode($raw, true);
        $base = [
            'players' => 0,
            'elections' => 0,
            'governments' => 0,
            'coalitions' => 0,
            'byParty' => [],
        ];
        return is_array($data) ? array_merge($base, $data) : $base;
    }

    private function writeCounters(array $counters): void
    {
        $path = $this->countersPath();
        $tmp = $path . '.' . getmypid() . '.tmp';
        if (@file_put_contents($tmp, json_encode($counters), LOCK_EX) !== false) {
            @rename($tmp, $path);
        }
    }

    private function bumpCounter(string $key, int $by = 1): void
    {
        $c = $this->counters();
        $c[$key] = (int) ($c[$key] ?? 0) + $by;
        $this->writeCounters($c);
    }

    private function bumpParty(string $party, bool $won): void
    {
        $c = $this->counters();
        $row = $c['byParty'][$party] ?? ['played' => 0, 'won' => 0];
        $row['played']++;
        if ($won) {
            $row['won']++;
        }
        $c['byParty'][$party] = $row;
        $this->writeCounters($c);
    }

    /** Games started, counted whether or not anybody finishes them. */
    public function countGameStarted(): void
    {
        $this->bumpCounter('started');
    }

    /**
     * The home screen's figures. Zero is a real answer here — a new
     * installation has had no players and should say so rather than invent
     * somebody.
     */
    public function summary(): array
    {
        $c = $this->counters();
        $parties = [];
        $totalParty = 0;
        foreach (($c['byParty'] ?? []) as $row) {
            $totalParty += (int) $row['played'];
        }
        foreach (($c['byParty'] ?? []) as $party => $row) {
            $parties[] = [
                'party' => $party,
                'played' => (int) $row['played'],
                'won' => (int) $row['won'],
                'share' => $totalParty > 0 ? (int) round(($row['played'] / $totalParty) * 100) : 0,
            ];
        }
        usort($parties, static fn($a, $b) => $b['played'] <=> $a['played']);

        return [
            'players' => (int) ($c['players'] ?? 0),
            'started' => (int) ($c['started'] ?? 0),
            'elections' => (int) ($c['elections'] ?? 0),
            'governments' => (int) ($c['governments'] ?? 0),
            'coalitions' => (int) ($c['coalitions'] ?? 0),
            'byParty' => $parties,
        ];
    }

    /**
     * The top players by score. Reads every profile, which is fine at this
     * size and honest about what it is; it would want an index long before it
     * wanted a rewrite.
     */
    public function leaderboard(int $limit = 10): array
    {
        $rows = [];
        foreach (glob($this->dir . '/*.json') ?: [] as $file) {
            $data = json_decode((string) @file_get_contents($file), true);
            if (!is_array($data) || empty($data['id'])) {
                continue;
            }
            $score = $this->scoreOf($data);
            if ($score <= 0) {
                continue;
            }
            $rows[] = [
                'name' => $data['name'],
                'portraitSeed' => $data['portraitSeed'],
                'score' => $score,
                'won' => (int) $data['verifiedWon'],
                'played' => (int) $data['verifiedPlayed'],
                'level' => $this->levelOf($data)['level'],
            ];
        }
        usort($rows, static fn($a, $b) => $b['score'] <=> $a['score'] ?: strcmp($a['name'], $b['name']));
        return array_slice($rows, 0, $limit);
    }
}
