<?php
/**
 * Game storage.
 * ------------------------------------------------------------------
 * A tiny interface plus a file-backed implementation. Shared hosting gives
 * us PHP and a filesystem, so that is what Version 1 uses. Swapping in MySQL
 * later means writing one more class with these five methods and changing
 * the line in bootstrap.php that constructs the store — nothing else.
 *
 * Writes go through an exclusive flock so two players acting at the same
 * moment cannot clobber each other's changes.
 */
declare(strict_types=1);

interface Store
{
    public function findByCode(string $code): ?array;
    public function findById(string $id): ?array;
    public function save(array $game): void;
    public function delete(string $id): void;

    /**
     * Read a game, hand it to $mutator, and write back whatever comes out —
     * all while holding the lock. Returns the updated game, or null if the
     * game does not exist. The mutator may return null to abort the write.
     */
    public function withLock(string $id, callable $mutator): ?array;

    /** Unfinished games a profile can still return to. */
    public function gamesForProfile(string $profileId): array;
}

final class FileStore implements Store
{
    private string $dir;

    public function __construct(string $dir)
    {
        $this->dir = rtrim($dir, '/\\');
        if (!is_dir($this->dir)) {
            @mkdir($this->dir, 0700, true);
        }
        $this->protectDirectory();
    }

    /** Belt and braces: the data directory must never be web-readable. */
    private function protectDirectory(): void
    {
        $htaccess = $this->dir . '/.htaccess';
        if (!file_exists($htaccess)) {
            @file_put_contents(
                $htaccess,
                "Require all denied\n<IfModule !mod_authz_core.c>\n  Deny from all\n</IfModule>\n"
            );
        }
        $index = $this->dir . '/index.html';
        if (!file_exists($index)) {
            @file_put_contents($index, '');
        }
    }

    private function pathFor(string $id): string
    {
        // Ids are generated by us and always hex, but never trust that here.
        $safe = preg_replace('/[^a-f0-9]/', '', strtolower($id));
        return $this->dir . '/game-' . $safe . '.json';
    }

    private function indexPath(): string
    {
        return $this->dir . '/codes.json';
    }

    public function findById(string $id): ?array
    {
        $path = $this->pathFor($id);
        if (!is_file($path)) {
            return null;
        }
        $raw = @file_get_contents($path);
        if ($raw === false || $raw === '') {
            return null;
        }
        $game = json_decode($raw, true);
        return is_array($game) ? $game : null;
    }

    public function findByCode(string $code): ?array
    {
        $id = $this->lookupCode($code);
        return $id === null ? null : $this->findById($id);
    }

    /** code -> id map, kept in one small file so lookups are a single read. */
    private function readIndex(): array
    {
        $path = $this->indexPath();
        if (!is_file($path)) {
            return [];
        }
        $raw = @file_get_contents($path);
        $map = $raw === false ? null : json_decode($raw, true);
        return is_array($map) ? $map : [];
    }

    private function writeIndex(array $map): void
    {
        $this->atomicWrite($this->indexPath(), json_encode($map, JSON_UNESCAPED_SLASHES));
    }

    private function lookupCode(string $code): ?string
    {
        $map = $this->readIndex();
        $key = strtoupper($code);
        return isset($map[$key]) ? (string) $map[$key] : null;
    }

    public function codeExists(string $code): bool
    {
        return $this->lookupCode($code) !== null;
    }

    public function save(array $game): void
    {
        $this->atomicWrite(
            $this->pathFor($game['id']),
            json_encode($game, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
        );

        $map = $this->readIndex();
        $map[strtoupper($game['code'])] = $game['id'];
        $this->writeIndex($map);
    }

    public function delete(string $id): void
    {
        $game = $this->findById($id);
        @unlink($this->pathFor($id));
        if ($game !== null) {
            $map = $this->readIndex();
            unset($map[strtoupper($game['code'])]);
            $this->writeIndex($map);
        }
    }

    public function withLock(string $id, callable $mutator): ?array
    {
        $path = $this->pathFor($id);
        if (!is_file($path)) {
            return null;
        }

        $handle = fopen($path, 'r+');
        if ($handle === false) {
            return null;
        }

        try {
            if (!flock($handle, LOCK_EX)) {
                return null;
            }
            $raw = stream_get_contents($handle);
            $game = json_decode($raw === false ? '' : $raw, true);
            if (!is_array($game)) {
                return null;
            }

            $updated = $mutator($game);
            if ($updated === null) {
                return $game; // mutator declined to change anything
            }

            $encoded = json_encode($updated, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
            ftruncate($handle, 0);
            rewind($handle);
            fwrite($handle, $encoded);
            fflush($handle);
            return $updated;
        } finally {
            flock($handle, LOCK_UN);
            fclose($handle);
        }
    }

    private function atomicWrite(string $path, string $contents): void
    {
        $tmp = $path . '.' . bin2hex(random_bytes(4)) . '.tmp';
        if (@file_put_contents($tmp, $contents, LOCK_EX) === false) {
            return;
        }
        @rename($tmp, $path);
    }

    /** Remove games untouched for longer than $maxAgeSeconds. */
    public function pruneOlderThan(int $maxAgeSeconds): int
    {
        $removed = 0;
        $cutoff = time() - $maxAgeSeconds;
        foreach (glob($this->dir . '/game-*.json') ?: [] as $file) {
            $raw = @file_get_contents($file);
            $game = $raw === false ? null : json_decode($raw, true);
            if (!is_array($game) || (int) ($game['updatedAt'] ?? 0) < $cutoff) {
                if (is_array($game) && isset($game['id'])) {
                    $this->delete((string) $game['id']);
                } else {
                    @unlink($file);
                }
                $removed++;
            }
        }
        return $removed;
    }

    public function activeGameCount(): int
    {
        return count(glob($this->dir . '/game-*.json') ?: []);
    }

    /**
     * Unfinished games one profile is still a part of.
     *
     * Reads every game file, which is fine at this size and honest about what
     * it is — a few dozen small files on shared hosting. It would want an
     * index long before it wanted a different database.
     *
     * Skips finished elections and any game the player explicitly ended:
     * ending is a decision, and the point of it is that the game stops
     * offering itself back.
     *
     * @return array<int, array{game:array, playerId:string}>
     */
    public function gamesForProfile(string $profileId): array
    {
        if ($profileId === '') {
            return [];
        }
        $out = [];
        foreach (glob($this->dir . '/game-*.json') ?: [] as $file) {
            $raw = @file_get_contents($file);
            $game = $raw === false ? null : json_decode($raw, true);
            if (!is_array($game)) {
                continue;
            }
            if (in_array($game['phase'] ?? '', ['government', 'hung'], true)) {
                continue;
            }
            foreach (($game['players'] ?? []) as $pid => $p) {
                if (($p['profileId'] ?? null) !== $profileId || !empty($p['endedByPlayer'])) {
                    continue;
                }
                $out[] = ['game' => $game, 'playerId' => (string) $pid];
            }
        }
        usort(
            $out,
            static fn($a, $b) => (int) ($b['game']['updatedAt'] ?? 0) <=> (int) ($a['game']['updatedAt'] ?? 0)
        );
        return $out;
    }
}
