/**
 * build-data.mjs
 * ------------------------------------------------------------------
 * Emits src/data/punjab-seats.js from the verified constituency list.
 *
 * Everything written here is REAL-WORLD REFERENCE DATA:
 *   number, name, district, reservation, region.
 * The one editorial addition is `settlement` (urban / semi-urban / rural),
 * a coarse game-design classification used to shape simulated voter
 * profiles. No simulated political support is written into this file --
 * the engine generates all of that at runtime from a seed.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const acs = JSON.parse(fs.readFileSync(path.join(HERE, 'acs.json'), 'utf8'));

/* Punjab's three historic cultural regions, by district.
   Majha 25 seats | Doaba 23 seats | Malwa 69 seats. */
const REGION_BY_DISTRICT = {
  Amritsar: 'Majha',
  'Tarn Taran': 'Majha',
  Gurdaspur: 'Majha',
  Pathankot: 'Majha',
  Jalandhar: 'Doaba',
  Hoshiarpur: 'Doaba',
  Kapurthala: 'Doaba',
  'Shahid Bhagat Singh Nagar': 'Doaba',
};

// City-ward and municipal-corporation seats.
const URBAN = new Set([
  3, 4, 7, 15, 16, 17, 18, 19, 27, 29, 34, 35, 36, 37, 43, 52, 53, 57, 60, 61,
  62, 63, 64, 65, 73, 76, 81, 86, 87, 92, 103, 105, 108, 111, 115,
]);

// District / tehsil towns with a substantial urban vote but a rural hinterland.
const SEMI_URBAN = new Set([
  5, 6, 11, 13, 14, 21, 23, 26, 28, 30, 31, 33, 38, 39, 40, 41, 45, 46, 47, 48,
  49, 50, 54, 55, 56, 58, 59, 67, 69, 70, 75, 77, 79, 80, 84, 85, 88, 89, 90,
  91, 93, 94, 95, 96, 98, 99, 100, 101, 102, 104, 106, 107, 109, 110, 112, 114,
  116,
]);

const seats = acs.map((row) => {
  const num = row[0];
  return {
    num,
    name: row[1],
    district: row[2],
    reservation: row[3],
    region: REGION_BY_DISTRICT[row[2]] || 'Malwa',
    settlement: URBAN.has(num) ? 'urban' : SEMI_URBAN.has(num) ? 'semi-urban' : 'rural',
  };
});

// Map labels for districts whose official name overruns its cell.
const SHORT_LABEL = {
  'Shahid Bhagat Singh Nagar': 'SBS Nagar',
  'S.A.S. Nagar': 'Mohali',
  'Sri Muktsar Sahib': 'Muktsar',
  'Fatehgarh Sahib': 'Fatehgarh S.',
};

const districts = {};
for (const s of seats) {
  if (!districts[s.district]) {
    districts[s.district] = {
      name: s.district,
      short: SHORT_LABEL[s.district] || s.district,
      region: s.region,
      seats: [],
    };
  }
  districts[s.district].seats.push(s.num);
}

const regions = {};
for (const s of seats) {
  if (!regions[s.region]) regions[s.region] = { name: s.region, seats: [], districts: [] };
  regions[s.region].seats.push(s.num);
  if (regions[s.region].districts.indexOf(s.district) === -1) {
    regions[s.region].districts.push(s.district);
  }
}

const body = [
  '/* GENERATED by tools/build-data.mjs - do not edit by hand.',
  ' *',
  ' * REAL-WORLD REFERENCE DATA: the 117 Punjab Legislative Assembly',
  ' * constituencies - number, name, district, SC reservation, cultural region.',
  ' * Verified against the Wikipedia list of Punjab Legislative Assembly',
  ' * constituencies and punjabdata.com district-wise listings (Aug 2026).',
  ' *',
  ' * `settlement` is an editorial game classification, not official data.',
  ' * No simulated political support lives in this file. */',
  'window.PG = window.PG || {};',
  'PG.PUNJAB_SEATS = ' + JSON.stringify(seats, null, 0) + ';',
  'PG.PUNJAB_DISTRICTS = ' + JSON.stringify(districts, null, 0) + ';',
  'PG.PUNJAB_REGIONS = ' + JSON.stringify(regions, null, 0) + ';',
  '',
].join('\n');

const out = path.join(HERE, '..', 'src', 'data', 'punjab-seats.js');
fs.writeFileSync(out, body);

console.log('seats: ' + seats.length);
console.log('districts: ' + Object.keys(districts).length);
console.log(
  'regions: ' +
    Object.values(regions)
      .map((r) => r.name + ' ' + r.seats.length)
      .join(', ')
);
console.log('urban ' + seats.filter((s) => s.settlement === 'urban').length +
  ' / semi ' + seats.filter((s) => s.settlement === 'semi-urban').length +
  ' / rural ' + seats.filter((s) => s.settlement === 'rural').length);
console.log('SC reserved: ' + seats.filter((s) => s.reservation === 'SC').length);
console.log('written ' + (fs.statSync(out).size / 1024).toFixed(1) + ' KB');
