/**
 * Generates simple/js/data/regions.js from the constituency list.
 *
 * Punjab's three regions are real geography, not a game invention: Majha is
 * the land between the Ravi and the Beas, Doaba the Bist Doab between the Beas
 * and the Sutlej, and Malwa everything south of the Sutlej. Every district
 * belongs to exactly one of them, and the mapping below is the conventional
 * one — it is not adjustable, because it is not a balance decision.
 *
 * What IS a balance decision is the grant each district pays while a player
 * holds every seat in it. That scales with the district's size, between the
 * floor and ceiling set in campaign-config.json, so a fourteen-seat district
 * is worth holding and a two-seat one is worth taking early.
 *
 *   node tools/build-regions.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, '..');
const SEATS = path.join(ROOT, 'simple', 'js', 'data', 'constituencies.js');
const CONFIG = path.join(ROOT, 'simple', 'api', 'campaign-config.json');
const OUT = path.join(ROOT, 'simple', 'js', 'data', 'regions.js');

/**
 * District to region. The three names are how Punjab describes itself; the
 * assignment follows the rivers.
 */
const REGION_OF = {
  // Majha — between the Ravi and the Beas.
  'Amritsar': 'majha',
  'Tarn Taran': 'majha',
  'Gurdaspur': 'majha',
  'Pathankot': 'majha',

  // Doaba — the Bist Doab, between the Beas and the Sutlej.
  'Jalandhar': 'doaba',
  'Kapurthala': 'doaba',
  'Hoshiarpur': 'doaba',
  'Shahid Bhagat Singh Nagar': 'doaba',

  // Malwa — south of the Sutlej.
  'Ludhiana': 'malwa',
  'Patiala': 'malwa',
  'Bathinda': 'malwa',
  'Sangrur': 'malwa',
  'Firozpur': 'malwa',
  'Faridkot': 'malwa',
  'Moga': 'malwa',
  'Sri Muktsar Sahib': 'malwa',
  'Barnala': 'malwa',
  'Mansa': 'malwa',
  'Fatehgarh Sahib': 'malwa',
  'Rupnagar': 'malwa',
  'S.A.S. Nagar': 'malwa',
  'Fazilka': 'malwa',
  'Malerkotla': 'malwa',
};

const REGIONS = [
  { id: 'majha', name: 'Majha', blurb: 'Between the Ravi and the Beas' },
  { id: 'doaba', name: 'Doaba', blurb: 'The Bist Doab, between the Beas and the Sutlej' },
  { id: 'malwa', name: 'Malwa', blurb: 'South of the Sutlej' },
];

/* ------------------------------------------------------------------ read */

const js = fs.readFileSync(SEATS, 'utf8');
const m = js.match(/CMP\.CONSTITUENCIES = (\[[\s\S]*?\]);/);
if (!m) {
  console.error('could not read the constituency list');
  process.exit(1);
}
const seats = JSON.parse(m[1]);
const config = JSON.parse(fs.readFileSync(CONFIG, 'utf8'));
const grantCfg = (config.territory || {}).grant || { min: 20000000, max: 300000000 };

/* -------------------------------------------------------------- validate */

const problems = [];
const byDistrict = new Map();
for (const seat of seats) {
  if (!byDistrict.has(seat.district)) byDistrict.set(seat.district, []);
  byDistrict.get(seat.district).push(seat.number);
}
for (const name of byDistrict.keys()) {
  if (!REGION_OF[name]) problems.push('no region for district: ' + name);
}
for (const name of Object.keys(REGION_OF)) {
  if (!byDistrict.has(name)) problems.push('region names a district that has no seats: ' + name);
}
if (!(grantCfg.min > 0 && grantCfg.max > grantCfg.min)) {
  problems.push('territory.grant needs min and max, with max above min');
}
if (problems.length) {
  console.error('regions are not valid:');
  problems.forEach((p) => console.error('  - ' + p));
  process.exit(1);
}

/* ---------------------------------------------------------------- build */

const sizes = [...byDistrict.values()].map((v) => v.length);
const smallest = Math.min(...sizes);
const largest = Math.max(...sizes);

/** A district's grant, scaled by how many seats it takes to hold. */
function grantFor(count) {
  const span = largest - smallest;
  const t = span > 0 ? (count - smallest) / span : 0;
  const raw = grantCfg.min + t * (grantCfg.max - grantCfg.min);
  // To the nearest lakh, so the figures read as round numbers.
  return Math.round(raw / 100000) * 100000;
}

const districts = [...byDistrict.entries()]
  .map(([name, numbers]) => ({
    id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
    name,
    region: REGION_OF[name],
    seats: numbers.sort((a, b) => a - b),
    grant: grantFor(numbers.length),
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

const body = `/**
 * Punjab's three regions, its districts, and what each district pays.
 * GENERATED by tools/build-regions.mjs — do not edit here.
 *
 * The regions and the districts they contain are real geography. The grant a
 * district pays while one player holds every seat in it is a game value, set
 * by tools/build-regions.mjs from the floor and ceiling in
 * api/campaign-config.json, and is not a real government grant of any kind.
 */
window.CMP = window.CMP || {};

CMP.REGIONS = ${JSON.stringify(REGIONS, null, 2)};

CMP.DISTRICTS = ${JSON.stringify(districts, null, 2)};

/** Which district a seat number belongs to. */
CMP.DISTRICT_OF_SEAT = (function () {
  var map = {};
  CMP.DISTRICTS.forEach(function (d) {
    d.seats.forEach(function (n) {
      map[n] = d.id;
    });
  });
  return map;
})();

CMP.getDistrict = function (id) {
  for (var i = 0; i < CMP.DISTRICTS.length; i++) {
    if (CMP.DISTRICTS[i].id === id) return CMP.DISTRICTS[i];
  }
  return null;
};

CMP.getRegion = function (id) {
  for (var i = 0; i < CMP.REGIONS.length; i++) {
    if (CMP.REGIONS[i].id === id) return CMP.REGIONS[i];
  }
  return null;
};

/** The region a seat number sits in. */
CMP.regionOfSeat = function (number) {
  var d = CMP.getDistrict(CMP.DISTRICT_OF_SEAT[number]);
  return d ? d.region : null;
};

/** Districts in one region. */
CMP.districtsInRegion = function (regionId) {
  return CMP.DISTRICTS.filter(function (d) {
    return d.region === regionId;
  });
};
`;

fs.writeFileSync(OUT, body);

const perRegion = {};
for (const d of districts) {
  perRegion[d.region] = perRegion[d.region] || { districts: 0, seats: 0, grant: 0 };
  perRegion[d.region].districts++;
  perRegion[d.region].seats += d.seats.length;
  perRegion[d.region].grant += d.grant;
}

const crore = (n) => '₹' + (n / 10000000).toFixed(2).replace(/\.00$/, '') + ' Cr';

console.log('districts: ' + districts.length + ', seats: ' + seats.length);
for (const r of REGIONS) {
  const p = perRegion[r.id];
  console.log(
    '  ' + r.name.padEnd(7) + p.districts + ' districts, ' +
    String(p.seats).padStart(3) + ' seats, ' + crore(p.grant).padStart(11) + ' a round if wholly held'
  );
}
console.log('grants: ' + crore(Math.min(...districts.map((d) => d.grant))) +
  ' (' + smallest + ' seats) to ' + crore(Math.max(...districts.map((d) => d.grant))) +
  ' (' + largest + ' seats)');
console.log('written: ' + path.relative(ROOT, OUT));
